-- 디지몬 이미지 경로 일괄 등록 (자동 생성, public/ 폴더의 정적 이미지 기준)
-- 공용 카탈로그이므로 UID 없이 바로 실행 가능합니다.
-- 퀀타몬은 이미지가 없어 제외되었습니다.

update public.digimons set image_url = '/%EC%95%84%EA%B5%AC%EB%AA%AC.png' where name = '아구몬';
update public.digimons set image_url = '/%EA%B7%B8%EB%A0%88%EC%9D%B4%EB%AA%AC.png' where name = '그레이몬';
update public.digimons set image_url = '/%EB%A9%94%ED%83%88%EA%B7%B8%EB%A0%88%EC%9D%B4%EB%AA%AC.png' where name = '메탈그레이몬';
update public.digimons set image_url = '/%EC%9B%8C%EA%B7%B8%EB%A0%88%EC%9D%B4%EB%AA%AC.png' where name = '워그레이몬';
update public.digimons set image_url = '/%EC%98%A4%EB%A9%94%EA%B0%80%EB%AA%AC.png' where name = '오메가몬';
update public.digimons set image_url = '/%EC%98%A4%EB%A9%94%EA%B0%80%EB%AA%AC%20%EB%A8%B8%EC%8B%9C%ED%92%80%EB%AA%A8%EB%93%9C.png' where name = '오메가몬 머시풀모드';
update public.digimons set image_url = '/%ED%8C%8C%ED%94%BC%EB%AA%AC.png' where name = '파피몬';
update public.digimons set image_url = '/%EA%B0%80%EB%A3%A8%EB%AA%AC.png' where name = '가루몬';
update public.digimons set image_url = '/%EC%9B%8C%EA%B0%80%EB%A3%A8%EB%AA%AC.png' where name = '워가루몬';
update public.digimons set image_url = '/%EB%A9%94%ED%83%88%EA%B0%80%EB%A3%A8%EB%AA%AC.png' where name = '메탈가루몬';
update public.digimons set image_url = '/%EC%83%A4%EC%9A%B0%ED%8A%B8%EB%AA%AC.png' where name = '샤우트몬';
update public.digimons set image_url = '/%EC%98%A4%EB%A9%94%EA%B0%80%EC%83%A4%EC%9A%B0%ED%8A%B8%EB%AA%AC.png' where name = '오메가샤우트몬';
update public.digimons set image_url = '/%EC%83%A4%EC%9A%B0%ED%8A%B8%EB%AA%ACX2.png' where name = '샤우트몬X2';
update public.digimons set image_url = '/%EC%83%A4%EC%9A%B0%ED%8A%B8%EB%AA%ACX3.png' where name = '샤우트몬X3';
update public.digimons set image_url = '/%EC%83%A4%EC%9A%B0%ED%8A%B8%EB%AA%ACX4.png' where name = '샤우트몬X4';
update public.digimons set image_url = '/%EC%83%A4%EC%9A%B0%ED%8A%B8%EB%AA%ACX5.png' where name = '샤우트몬X5';
update public.digimons set image_url = '/%EC%83%A4%EC%9A%B0%ED%8A%B8%EB%AA%ACDX.png' where name = '샤우트몬DX';
update public.digimons set image_url = '/%EC%83%A4%EC%9A%B0%ED%8A%B8%EB%AA%ACX7.png' where name = '샤우트몬X7';
update public.digimons set image_url = '/%EC%83%A4%EC%9A%B0%ED%8A%B8%EB%AA%ACX7%20%EC%8A%88%ED%8E%98%EB%A6%AC%EC%98%AC%EB%AA%A8%EB%93%9C.png' where name = '샤우트몬X7 슈페리올모드';
update public.digimons set image_url = '/%EB%8F%84%EC%82%AC%EB%AA%AC.png' where name = '도사몬';
update public.digimons set image_url = '/%EC%83%A4%ED%81%AC%EB%9D%BC%EB%AA%AC.png' where name = '샤크라몬';
update public.digimons set image_url = '/%EC%83%A4%ED%81%AC%EB%9D%BC%EB%AA%AC(%EA%B0%81%EC%84%B1).png' where name = '샤크라몬*(각성)';
update public.digimons set image_url = '/%EC%BF%A0%EC%A6%88%ED%95%98%EB%AA%AC.png' where name = '쿠즈하몬';
update public.digimons set image_url = '/%EC%BF%A0%EC%A6%88%ED%95%98%EB%AA%AC%20%EB%AC%B4%EB%85%80%EB%AA%A8%EB%93%9C.png' where name = '쿠즈하몬 무녀모드';
update public.digimons set image_url = '/%EA%B8%B8%EB%AA%AC.png' where name = '길몬';
update public.digimons set image_url = '/%EA%B7%B8%EB%9D%BC%EC%9A%B0%EB%AA%AC.png' where name = '그라우몬';
update public.digimons set image_url = '/%EB%A9%94%EA%B0%80%EB%A1%9C%EA%B7%B8%EB%9D%BC%EC%9A%B0%EB%AA%AC.png' where name = '메가로그라우몬';
update public.digimons set image_url = '/%EB%93%80%ED%81%AC%EB%AA%AC.png' where name = '듀크몬';
update public.digimons set image_url = '/%EB%93%80%ED%81%AC%EB%AA%AC(%EA%B0%81%EC%84%B1).png' where name = '듀크몬*(각성)';
update public.digimons set image_url = '/%EB%93%80%ED%81%AC%EB%AA%AC%20%ED%81%AC%EB%A6%BC%EC%A1%B4%EB%AA%A8%EB%93%9C(%EA%B0%81%EC%84%B1).png' where name = '듀크몬 크림존모드*(각성)';
update public.digimons set image_url = '/%EB%93%80%ED%81%AC%EB%AA%AC%20%ED%81%AC%EB%A6%BC%EC%A1%B4%EB%AA%A8%EB%93%9C.png' where name = '듀크몬 크림존모드';
update public.digimons set image_url = '/%EC%97%90%EC%98%A4%EC%8A%A4%EB%AA%AC(%EC%84%B1%EC%88%99%EA%B8%B0).png' where name = '에오스몬(성숙기)';
update public.digimons set image_url = '/%EC%97%90%EC%98%A4%EC%8A%A4%EB%AA%AC(%EC%99%84%EC%A0%84%EC%B2%B4).png' where name = '에오스몬(완전체)';
update public.digimons set image_url = '/%EC%97%90%EC%98%A4%EC%8A%A4%EB%AA%AC(%EA%B6%81%EA%B7%B9%EC%B2%B4).png' where name = '에오스몬(궁극체)';
update public.digimons set image_url = '/%EC%8B%9C%EB%A6%AC%EC%9A%B0%EC%8A%A4%EB%AA%AC.png' where name = '시리우스몬';
update public.digimons set image_url = '/%EC%95%94%ED%94%BC%EB%AA%AC.png' where name = '암피몬';
update public.digimons set image_url = '/%EB%94%94%EC%96%B4%EB%B9%84%ED%8A%B8%EB%AA%AC.png' where name = '디어비트몬';
update public.digimons set image_url = '/%EB%B8%94%EB%A3%B8%EB%A1%9C%EB%93%9C%EB%AA%AC.png' where name = '블룸로드몬';
update public.digimons set image_url = '/%EB%A6%B4%EB%A6%AC%EB%AA%AC.png' where name = '릴리몬';
update public.digimons set image_url = '/%EB%A1%9C%ED%84%B0%EC%8A%A4%EB%AA%AC.png' where name = '로터스몬';
update public.digimons set image_url = '/%EB%A1%9C%EC%A0%9C%EB%AA%AC.png' where name = '로제몬';
update public.digimons set image_url = '/%EB%9D%BC%ED%94%8C%EB%A0%88%EC%8B%9C%EB%AA%AC.png' where name = '라플레시몬';
update public.digimons set image_url = '/%ED%8E%98%EC%96%B4%EB%A6%AC%EB%AA%AC.png' where name = '페어리몬';
update public.digimons set image_url = '/%EC%9B%8C%EA%B7%B8%EB%A0%88%EC%9D%B4%EB%AA%AC(%EA%B0%81%EC%84%B1).png' where name = '워그레이몬*(각성)';
update public.digimons set image_url = '/%EB%A9%94%ED%83%88%EA%B0%80%EB%A3%A8%EB%AA%AC(%EA%B0%81%EC%84%B1).png' where name = '메탈가루몬*(각성)';
update public.digimons set image_url = '/%EC%A7%80%EB%93%9C%EB%B0%80%EB%A0%88%EB%8B%88%EC%97%84%EB%AA%AC(%EA%B0%81%EC%84%B1).png' where name = '지드밀레니엄몬*(각성)';
update public.digimons set image_url = '/%ED%99%A9%EC%A0%9C%EB%93%9C%EB%9D%BC%EB%AA%AC%20%ED%8C%94%EB%9D%BC%EB%94%98%EB%AA%A8%EB%93%9C(%EA%B0%81%EC%84%B1).png' where name = '황제드라몬 팔라딘모드*(각성)';
update public.digimons set image_url = '/%EB%94%94%EC%95%84%EB%B8%94%EB%A1%9C%EB%AA%AC.png' where name = '디아블로몬';
update public.digimons set image_url = '/%EC%95%84%EB%A7%88%EA%B2%8C%EB%AA%AC%5B%ED%95%A9%EC%84%B1%EC%B2%B4%5D.png' where name = '아마게몬[합성체]';
update public.digimons set image_url = '/%ED%99%A9%EC%A0%9C%EB%93%9C%EB%9D%BC%EB%AA%AC%20%ED%8C%8C%EC%9D%B4%ED%84%B0%EB%AA%A8%EB%93%9C(%EA%B0%81%EC%84%B1).png' where name = '황제드라몬 파이터모드*(각성)';
update public.digimons set image_url = '/%EC%95%8C%ED%8C%8C%EB%AA%AC%20%EC%99%95%EB%A3%A1%EA%B2%80%5B%EA%B7%B9%EC%9D%98%5D.png' where name = '알파몬 왕룡검[극의]';
update public.digimons set image_url = '/%EC%95%84%EA%B7%B8%EB%8B%88%EB%AA%AC.png' where name = '아그니몬';
update public.digimons set image_url = '/%EC%B0%A8%ED%81%AC%EB%AA%AC.png' where name = '차크몬';
update public.digimons set image_url = '/%EC%95%8C%EB%B3%BC%EB%AA%AC.png' where name = '알볼몬';
update public.digimons set image_url = '/%EA%B7%B8%EB%A1%9C%ED%8A%B8%EB%AA%AC.png' where name = '그로트몬';
update public.digimons set image_url = '/%EB%B3%BC%ED%94%84%EB%AA%AC.png' where name = '볼프몬';
update public.digimons set image_url = '/%EB%B8%8C%EB%A6%AC%EC%B8%A0%EB%AA%AC.png' where name = '브리츠몬';
update public.digimons set image_url = '/%EB%9D%BC%EB%82%98%EB%AA%AC.png' where name = '라나몬';
update public.digimons set image_url = '/%EB%A0%88%EB%B2%A0%EB%AA%AC.png' where name = '레베몬';
update public.digimons set image_url = '/%EB%A8%B8%ED%81%90%EB%A0%88%EB%AA%AC.png' where name = '머큐레몬';
update public.digimons set image_url = '/%EB%A3%A8%EC%B2%B4%EB%AA%AC%20%EC%82%AC%ED%83%84%EB%AA%A8%EB%93%9C%5B%EA%B7%B9%EC%9D%98%5D.png' where name = '루체몬 사탄모드[극의]';
update public.digimons set image_url = '/%EB%9D%BC%EC%8A%A4%ED%8A%B8%20%EC%97%90%EB%B3%BC%EB%A3%A8%EC%85%98%20%EC%9D%B8%EC%97%B0.png' where name = '라스트 에볼루션 : 인연';
update public.digimons set image_url = '/%EB%B0%80%EB%A0%88%EB%8B%88%EC%97%84%EB%AA%AC.png' where name = '밀레니엄몬';
update public.digimons set image_url = '/%EA%B0%93%EB%93%9C%EB%9D%BC%EB%AA%AC.png' where name = '갓드라몬';
update public.digimons set image_url = '/%ED%99%80%EB%A6%AC%EB%93%9C%EB%9D%BC%EB%AA%AC.png' where name = '홀리드라몬';
update public.digimons set image_url = '/%EB%B8%8C%EB%A6%AC%ED%8A%B8%EB%9D%BC%EB%AA%AC.png' where name = '브리트라몬';
update public.digimons set image_url = '/%EC%8A%88%ED%8A%B8%EB%AA%AC.png' where name = '슈트몬';
update public.digimons set image_url = '/%EB%B8%94%EB%A6%AC%EC%9E%90%EB%AA%AC.png' where name = '블리자몬';
update public.digimons set image_url = '/%ED%8E%98%ED%83%88%EB%93%9C%EB%9D%BC%EB%AA%AC.png' where name = '페탈드라몬';
update public.digimons set image_url = '/%EA%B8%B0%EA%B0%80%EC%8A%A4%EB%AA%AC.png' where name = '기가스몬';
update public.digimons set image_url = '/%EA%B0%80%EB%A3%B8%EB%AA%AC.png' where name = '가룸몬';
update public.digimons set image_url = '/%EB%B3%BC%EA%B7%B8%EB%AA%AC.png' where name = '볼그몬';
update public.digimons set image_url = '/%EC%B9%BC%EB%A7%88%EB%9D%BC%EB%AA%AC.png' where name = '칼마라몬';
update public.digimons set image_url = '/%EC%B9%B4%EC%9D%B4%EC%A0%80%EB%A0%88%EC%98%A4%EB%AA%AC.png' where name = '카이저레오몬';
update public.digimons set image_url = '/%EC%84%B8%ED%94%BC%EB%A1%9C%ED%8A%B8%EB%AA%AC.png' where name = '세피로트몬';
update public.digimons set image_url = '/%EC%8A%A4%EC%82%AC%EB%85%B8%EC%98%A4%EB%AA%AC%5B%EA%B7%B9%EC%9D%98%5D.png' where name = '스사노오몬[극의]';
update public.digimons set image_url = '/%EB%A6%AC%EB%A6%AC%EC%8A%A4%EB%AA%ACX%20%5B%EA%B0%81%EC%84%B1%5D.png' where name = '리리스몬X [각성]';
update public.digimons set image_url = '/%ED%8C%8C%EC%9B%8C%EB%93%9C%EB%9D%BC%EB%AA%AC.png' where name = '파워드라몬';
update public.digimons set image_url = '/%EB%8D%98%EB%8D%B0%EB%B8%94%EB%AA%AC.png' where name = '던데블몬';
update public.digimons set image_url = '/%EC%84%B8%EB%9D%BC%ED%94%BC%EB%AA%AC.png' where name = '세라피몬';
update public.digimons set image_url = '/%EB%B0%94%EC%9D%B4%ED%82%B9%EB%AA%AC.png' where name = '바이킹몬';
update public.digimons set image_url = '/%ED%97%A4%EB%9D%BC%ED%81%B4%EB%A0%88%EC%8A%A4%EC%BA%85%ED%85%8C%EB%A6%AC%EB%AA%AC.png' where name = '헤라클레스캅테리몬';
update public.digimons set image_url = '/%ED%8E%98%EB%8B%89%EC%8A%A4%EB%AA%AC.png' where name = '페닉스몬';
update public.digimons set image_url = '/%EC%95%84%EB%B0%94%EB%8F%84%EB%AA%AC.png' where name = '아바도몬';
update public.digimons set image_url = '/%EC%98%A4%ED%8C%8C%EB%8B%88%EB%AA%AC.png' where name = '오파니몬';
update public.digimons set image_url = '/%EC%95%84%EB%B0%94%EB%8F%84%EB%AA%AC%20%EC%BD%94%EC%96%B4.png' where name = '아바도몬 코어';
update public.digimons set image_url = '/%EC%95%8C%ED%8C%8C%EB%AA%AC%20%EC%99%95%EB%A3%A1%EA%B2%80(%EA%B0%81%EC%84%B1).png' where name = '알파몬 왕룡검*(각성)';
update public.digimons set image_url = '/%EC%98%A4%EB%A9%94%EA%B0%80%EB%AA%ACX%20%5B%EA%B7%B9%EC%9D%98%5D.png' where name = '오메가몬X [극의]';
update public.digimons set image_url = '/%EC%95%84%ED%8F%B4%EB%A1%9C%EB%AA%AC.png' where name = '아폴로몬';
update public.digimons set image_url = '/%EB%8B%A4%ED%81%AC%EB%84%A4%EC%8A%A4%EB%B0%94%EA%B7%B8%EB%9D%BC%EB%AA%AC.png' where name = '다크네스바그라몬';
